version: "3.8"
services:
     mongodb:
        image: mongo
        container_name: mongodb
        ports:
            - 27017:27017
        volumes:
            - data:/data
        environment:
          - MONGO_INITDB_ROOT_USERNAME=rootuser
          - MONGO_INITDB_ROOT_PASSWORD=rootpass
          
     mongo-express:
        image: mongo-express
        container_name: mongo-express
        ports:
            - 8081:8081
        environment:
          - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
          - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
          - ME_CONFIG_MONGODB_SERVER=mongodb
          
          
     student-service:
       image: student-service
       container_name: student-service
       build: ./
       links:
         - mongodb
       depends_on:
         - mongodb
       environment:
         - SPRING_DATA_MONGODB_HOST=mongodb
         - SPRING_DATA_MONGODB_PORT=27017
         - SPRING_DATA_MONGODB_DATABASE=amigoscode      
       ports:
          - "8080:8080"

volumes:
 data: {}

networks:
  default:
    name: mongodb_network